### ISSUE TITLE
[Feature] 좋아요 API 구현

### ISSUE THREAD

**Issue by tenius10** [Apple-Square/moment-backend#15]
### 📄 Describe
마음에 드는 게시글과 댓글에 좋아요 표시를 할 수 있는 기능입니다.
작성자 본인은 좋아요를 누를 수 없습니다.

### ✅ Tasks
- [x] 게시글 좋아요 API
- [x] 게시글 좋아요 취소 API
- [x] 댓글 좋아요 API
- [x] 댓글 좋아요 취소 API
