### ISSUE TITLE
[Feature] 사용자 프로필 사진 추가

### ISSUE THREAD

**Issue by tenius10** [Apple-Square/moment-backend#17]
### 📄 Describe
사용자 정보에 프로필 사진을 추가합니다.

### ✅ Tasks
- [x] 나의 프로필 조회
- [x] 프로필 사진 설정
- [x] 프로필 사진 설정 해제
